<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Professional_sc-AxjAm eZoZgv</name>
   <tag></tag>
   <elementGuidId>0101d58f-54ea-4edf-a32b-8e799023c057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div[3]/div[2]/label/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-AxjAm.eZoZgv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-AxjAm eZoZgv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layouts__NonMobileWrapper-sc-1xal4ev-2 kNsdTi&quot;]/div[@class=&quot;sc-AxjAm AuthWrapper__Root-sc-122bof5-0 ewpkP&quot;]/div[@class=&quot;sc-AxjAm leUryK&quot;]/div[@class=&quot;sc-AxjAm ceCCet&quot;]/form[1]/div[@class=&quot;sc-AxjAm enXcES&quot;]/div[@class=&quot;sc-AxjAm lfZjtT&quot;]/label[@class=&quot;sc-AxjAm SignupForm___StyledBox-sc-1rgcjx5-0 kgWeAY&quot;]/div[@class=&quot;sc-AxjAm fnXZrJ&quot;]/div[@class=&quot;sc-AxjAm kqtnKp&quot;]/div[@class=&quot;sc-AxjAm eZoZgv&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div[3]/div[2]/label/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
