<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_r_1e3bc3</name>
   <tag></tag>
   <elementGuidId>cb6f9409-9e81-4e55-96b7-99b55e157463</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq25wnxGzVoIr3VRVknRNclihtK5WjdhAay3FQdhTC1eJ9zllQCd6xKVq_gn7LfzjFzjb28pltx9sZJ9cfVy9OvWrrhL0110GiXJR20sHEdUyqAsTndtno5swQ54IdufswxYFRp2a7_YXz6j1q6TSmwymAewC7bX25pUT-cO8fsfZyDIgpiinZGGmPzIeoeH3heWjtJGW&amp;k=6Ldx5z8UAAAAAKDtEYz7LzSXs21f30MIYoreLL5u</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Kata Platform/iframe_html1body1div4div4iframe1_c-gu5mtu5zwp07</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq25wnxGzVoIr3VRVknRNclihtK5WjdhAay3FQdhTC1eJ9zllQCd6xKVq_gn7LfzjFzjb28pltx9sZJ9cfVy9OvWrrhL0110GiXJR20sHEdUyqAsTndtno5swQ54IdufswxYFRp2a7_YXz6j1q6TSmwymAewC7bX25pUT-cO8fsfZyDIgpiinZGGmPzIeoeH3heWjtJGW&amp;k=6Ldx5z8UAAAAAKDtEYz7LzSXs21f30MIYoreLL5u')])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
